name: myportfolio_getx_mvvm
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.5
  flutter_svg: ^2.0.10+1
  pie_chart: ^5.4.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  convex_bottom_bar: ^3.2.0
  syncfusion_flutter_pdfviewer: ^24.2.9
  flutter_pdfview: ^1.3.2

  flutter_resume_template:
    # When depending on this package from a real application you should use:
    #   flutter_resume_template: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/pdf/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
